apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2 # Número de réplicas que se van a tener
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: investigacion1 # Asegúrar de que esta imagen exista o esté construida
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000 # Puerto en el que la API está escuchando
              protocol: TCP
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
