apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 4000 # Puerto interno del servicio (dentro del clúster)
      targetPort: 4000 # Puerto dentro del contenedor que la API está escuchando
      nodePort: 30000 # Puerto que se expone en el nodo (accesible fuera del clúster)
  type: NodePort
