apiVersion: v1
kind: Service
metadata:
  name: api-web-lis-loadbalancer
spec:
  selector:
    app: api-web-lis
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
